### ISSUE TITLE
[REQUEST] Kronos database

### ISSUE THREAD

**Issue by cnolimes** [shagu/shaguquest#10]
Hey, Shagu!

I'm wondering if you will be so kind to implement a parallel DB for the kronos server, because some spawn locations are different on the server. For example, the Rich Thorium Vein locations differentiate from the current DB that shaguquest show. Currently it shows the [wow-one](http://www.wow-one.com/database/index.php?object=175404) locations but the vein can be found as shown in [vanilla-gaming](http://db.vanillagaming.org/?object=175404) and [kronos](https://vanilla-twinhead.twinstar.cz/?object=175404) databases only.

If you don't feel like doing it, can you please tell me how to do it myself ?

Regards

KS

**Comment by Muehe** [comment]
@cnolimes In the 8.0 branch the DB used is [classicdb](https://github.com/classicdb/database), which is the cmangos DB. Before we were using mangos DB, so the new Data should be much closer to Kronos (which forked from cmangos). The beta should be out soon™.

**Comment by Muehe** [comment]
@cnolimes The beta is here. Hope it matches your needs! Btw. now you know why there is a ™ behind soon. :smile: Seriously though, sorry for the delay.
