### ISSUE TITLE
a few things

### ISSUE THREAD

**Issue by TinyLittleBits** [shagu/shaguquest#11]
- quest journal: collapse/expand buttons not working and sometimes not even displaying correctly ( glowing red ball instead of the icon - )

- quest journal: abandon quest provokes errors and sometimes abandon a quest that wasn't selected instead of the one selected (top priority).

- tooltip: related mobs to quests working randomly but most of the time never.

- tooltip: like many I'm using Questie beside ShaguQuest, I keep the SQ journal, Questie tracker, and would like to use the Questie infos in tooltip but they don't show up anymore because of a conflict with SQ.

I don't use the arrow of Questie and SQ indicators are better on map and more precise than Questie but.. they don't show on minimap :/ So the dream would be: a better looking SQ quest journal, PfUI style, with SQ indicators in minimap; the use of ? instead of ! icon for completed quest, like in Questie, the working tooltip infos of Questie and a working tracker (hide completed lines x/xx items or mobs).

o/

**Comment by Muehe** [comment]
Are you referring to the current 7.0 version? Because 8.0 Beta is on its way, you can see its current progress [on this branch](https://github.com/shagu/shaguquest/tree/finishedQuests). Also Questie 4.0 is currently being worked on and will include much more and better data.

**Comment by Muehe** [comment]
@shagu Do you have a version of EQL3 we could distribute as a replacement? Also, aero gave me your Discord handle, I sent you friends request.

**Comment by TinyLittleBits** [comment]
ShaguQuest v7.2
- the tooltip conflict with Questie has been solved with Questie v3.68

**Comment by Muehe** [comment]
@TinyLittleBits The 8.0 beta has arrived. Give it a try, it should resolve your tooltip issue (with Questie doing the tooltips, that is). Since your report concerns an old version which isn't going to be updated I am closing here. If you find any problems with the 8.0 version then new bug reports would be greatly appreciated. You can download the beta [here](https://github.com/shagu/shaguquest/releases).
