### ISSUE TITLE
Question mark icon displayed for map notes

### ISSUE THREAD

**Issue by Talyrius** [shagu/ShaguQuest#14]
Using 8.0 Beta 1, the question mark icon is being displayed on the map for quest notes instead of the multicolored blips seen in past versions:
![image](https://cloud.githubusercontent.com/assets/1068810/22855686/fa527aea-f038-11e6-99d9-170bbc339781.png)

![image](https://cloud.githubusercontent.com/assets/1068810/22855570/8ec3bb00-f037-11e6-8413-7ed8405b5237.png)

**Comment by Muehe** [comment]
Thanks for the report. Must have some error in my copy script, not the first problem like this... I'm in the process of moving (and renaming) the repo though, since shagu is focused on pfUI and real life. Will drop a link here when I'm done and fix this on the new repo. Same for #13.

**Comment by shagu** [comment]
https://github.com/Muehe/classicdb
