### ISSUE TITLE
ShaguDB: a nil value

### ISSUE THREAD

**Issue by Henxt** [shagu/ShaguQuest#16]
Getting all the time the same error in ShaguDB:

Interface\AddOns\ShaguDB\ShaguDB_GUI.lua:315: attempt to index field `?' (a nil value)
Picture: http://imgur.com/a/DqCit

What could it be?

Henxt

**Comment by shagu** [comment]
This project is abandoned and has been superseeded by pfQuest (https://github.com/shagu/pfQuest).

This issue is no longer valid for the new pfQuest addon.
