### ISSUE TITLE
How would one go by to add TBC information to this?

### ISSUE THREAD

**Issue by Larsy93** [shagu/ShaguQuest#17]
How would one go by to add TBC information to this?

The addon works perfectly in TBC without any modifications, the only thing missing is the data from TBC

**Comment by shagu** [comment]
I already put some effort in, to make it run on TBC. But it's still too far away from being "perfect". There will be a TBC branch as soon as I'm happy with the result.

**Comment by shagu** [comment]
PS: You can use the export scripts on the mangos-one or cmangos-tbc database to add the missing tbc data

**Comment by Larsy93** [comment]
Om not sure in tech-savvy enough to do that :/

**Comment by Larsy93** [comment]
Btw, when i tried it on a 2.4.3 server i couldnt find anything wrong

**Comment by Larsy93** [comment]
I just changed the toc to 20400 & removed the cartographer dependency cus it did not detect the TBC version or atleast not My version
