### ISSUE TITLE
Unable to Link Quests in Chat

### ISSUE THREAD

**Issue by t3hWheez** [shagu/ShaguQuest#18]
When linking a quest from the EQL, it only copies text and not the actual link itself.

**Comment by Muehe** [comment]
Did you do a Ctrl+Click instead of Shift+Click? To post a link you have to Shift+Click.

**Comment by t3hWheez** [comment]
I am trying to Shift Click it, it copies the text like [Quest Name] but it's not actually yellow and clickable.

**Comment by Muehe** [comment]
That's weird. For me it works quite well. Maybe you are using an older version? You can find the latest stable version [here](https://github.com/shagu/ShaguQuest/releases/latest) (v7.2). After Shift+Clicking a quest it looks like this for me:

![screenshot_2017-06-13_19-53-18](https://user-images.githubusercontent.com/8838573/27096706-37ed4ed6-5072-11e7-8064-7ca7a2f8f7d9.png)

![screenshot_2017-06-13_19-56-06](https://user-images.githubusercontent.com/8838573/27096751-6327de9a-5072-11e7-81c5-9b21c64f48a1.png)

**Comment by t3hWheez** [comment]
I went one by one and figured out it's Questie that causes this issue to happen.  Even with everything disabled with Questie the lone addon, quest linking still does not work.  Closing this issue.

**Comment by Muehe** [comment]
Mind to let me know which version of Questie you are using? 3.69 I guess?

**Comment by t3hWheez** [comment]
I went over to the git for Questie and found that 3.70 had fixed this issue via its tracker.  I upgraded to its dev build and appears resolved.

**Comment by Muehe** [comment]
The dev build has a bug when turning in Quests currently, I wouldn't recommend using it. If you want to anyway, this is a one-line fix for it, but this breaks tracker behaviour (you have to re-track quests all the time):

```diff
diff --git a/!Questie/Modules/QuestieTracker.lua b/!Questie/Modules/QuestieTracker.lua
index f934170..a333a4f 100644
--- a/!Questie/Modules/QuestieTracker.lua
+++ b/!Questie/Modules/QuestieTracker.lua
@@ -1058,6 +1058,7 @@ function QuestieTracker:BlizzardHooks()
         function RemoveQuestWatch(questIndex)
             local prevQuestLogSelection = QGet_QuestLogSelection();
             local questName, level, questTag, isHeader, isCollapsed, isComplete = QGet_QuestLogTitle(questIndex);
+            if (questName == nil) then return; end
             QSelect_QuestLogEntry(questIndex);
             local questText, objectiveText = QGet_QuestLogQuestText();
             local hash = Questie:getQuestHash(questName, level, objectiveText);
```
