### ISSUE TITLE
Item Search

### ISSUE THREAD

**Issue by cnolimes** [shagu/shaguquest#2]
Greetings!

Using this addon since patch 4.2 and I want to express my gratitude of your work. It helped me and keeps helping me a lot! However, /shagu item Item Name never worked for me. Typing the command does nothing but triggering a system message "Search: The item I'm looking for". I'm using an English client. Also, the newest release (6.1) is giving me the following error "...\ShaguQuest . lua : 282 : bad argument # 2 to ` strfind' (string expected, got nil)" every time I'm trying to search a game object consisted of 2 or more words, such as: Iron Deposit, Mithril Deposit, Gold Vein, Truesilver Vein etc. via /shagu spawn command. The command /shagu item <Item> doesn't even trigger the system msg I mentioned above (6.1 release)

Any help will be super appreciated.

**Comment by shagu** [comment]
Hi, it looks like you having WHDB enabled.
Many people reported this errors if using ShaguQuest together with WHDB.

This is because ShaguQuest uses the same variable names for zoneData and itemData as WHDB.
I will fix this on 6.2. Please be patient or disable WHDB.

**Comment by cnolimes** [comment]
Your advice solved the problem!

Thank you very much for the experience you are providing to us, Shagu! Keep up the lovely work.

Closing the issue
