### ISSUE TITLE
Localization: zhCN

### ISSUE THREAD

**Issue by wowmacro** [shagu/ShaguQuest#4]
not work with zhCN :(

**Comment by wowmacro** [comment]
fixed some error. but I cant fix this

Lua error with : EQL3_ShaguDB.Lua:72 and 182

bad argument #1 to `strfind'

I tried to change "(.*) killed" to "已杀死(.*)". but not working.

**Comment by shagu** [comment]
Sorry, I can't help with that,
I don't speak zhCN and don't have a zhCN client to test against.

**Comment by shagu** [comment]
In case you want to check: https://github.com/shagu/ShaguQuest/releases/tag/8.0loc

But you'll most probably have to fix stuff on your own.

**Comment by shagu** [comment]
This project is abandoned and has been superseeded by pfQuest (https://github.com/shagu/pfQuest).

pfQuest does support all gameclients. :)
