### ISSUE TITLE
/shagu vendor command

### ISSUE THREAD

**Issue by cnolimes** [shagu/shaguquest#6]
Greetings, Shagu!

I've noticed recently that sometimes /shagu vendor <item> does not add any marks on the map. An addon message is recieved that the item can be found at: but nothing really appears. Relog usually solves the problem but is there any way to fix this?

Any help will be appreciated!

Best regards

**Comment by shagu** [comment]
Hi,
Could you please check if this problem still occurs with the lates 7.0beta of ShaguDB?

Greets

**Comment by cnolimes** [comment]
The version is 6.7. Just downloaded the 7.0 beta and no problems so far. 
Thank you very much!

Regards

**Comment by cnolimes** [comment]
The same problem just occured, tried to look for Symbol of Kings.

**Comment by Muehe** [comment]
@cnolimes You can use [this Cartographer](https://github.com/Muehe/Cartographer) to fix tooltip overlay. It also adds some features as note size scroll and greater range for map size scroll (up to 10x normal size), which helps with seeing notes partially overlaying each other.

**Comment by Muehe** [comment]
Fixed in bc7865e9f20f28648209c68996d0a086c2dc5d98
